# Generated by Django 4.2.1 on 2023-05-23 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0002_review_rating_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
