# Generated by Django 4.2.1 on 2023-05-23 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_rename_favorites_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='recipe.recipe'),
        ),
        migrations.AlterField(
            model_name='review',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recipe.recipe'),
        ),
    ]
